### ISSUE TITLE
Permission denied when trying to commit

### ISSUE THREAD

**Issue by atruszkowska** [SCOREC/xgcm_data#1]
@cwsmith @eisungy I'm getting a permission denied when I'm trying to commit to this repo. I'm trying to upload the model and mesh needed for recently developed XGCM tests. Any idea what this could be? Thanks!

**Comment by cwsmith** [comment]
I just gave the fusion team write access.  Please try again.

**Comment by atruszkowska** [comment]
@cwsmith it worked now, thank you. Closing the issue.
